package com.revature.banking.models;

import java.util.Objects;

public class Transaction {

    private String id; //Generated by Save
    private String date; //Generated by Save
    private String type; //Generated by Transaction Service
    private Double amount; //Generated by Transaction Service
    private Double newBalance; // Generated by Transaction Service and DOA
    private Account account; //Found with Account Service
    private AppUser owner; //Found with UserService


    public Transaction(){}

    public Transaction(String date, String type) {
        this.date = date;
        this.type = type;
    }


    public Transaction(String date, String type, Double amount) {
        this.date = date;
        this.type = type;
        this.amount = amount;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Double getAmount() {
        return amount;
    }

    public void setAmount(Double amount) {
        this.amount = amount;
    }

    public Double getNewBalance() {
        return newBalance;
    }

    public void setNewBalance(Double newBalance) {
        this.newBalance = newBalance;
    }

    public Account getAccount() {
        return account;
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    public AppUser getOwner() {
        return owner;
    }

    public void setOwner(AppUser owner) {
        this.owner = owner;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Transaction that = (Transaction) o;
        return Objects.equals(id, that.id) && Objects.equals(date, that.date) && Objects.equals(type, that.type) && Objects.equals(amount, that.amount) && Objects.equals(newBalance, that.newBalance) && Objects.equals(account, that.account) && Objects.equals(owner, that.owner);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, date, type, amount, newBalance, account, owner);
    }

    @Override
    public String toString() {
        return "Transaction{" +
                "id='" + id + '\'' +
                ", date='" + date + '\'' +
                ", type='" + type + '\'' +
                ", amount=" + amount +
                ", newBalance=" + newBalance +
                ", account=" + account +
                ", owner=" + owner +
                '}';
    }
}
